apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: top10lists
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /top10movies
            pathType: Prefix
            backend:
              service:
                name: top10movies
                port:
                  name: http
          - path: /top10games
            pathType: Prefix
            backend:
              service:
                name: top10games
                port:
                  name: http
          - path: /top10songs
            pathType: Prefix
            backend:
              service:
                name: top10songs
                port:
                  name: http

