apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-service.fullname" . }}
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "simple-service.selectorLabels" . | nindent 4 }}

