apiVersion: v1
kind: Service
metadata:
  name: top10songs
spec:
  type: ClusterIP
  selector:
    app: top10songs
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: top10songs
spec:
  selector:
    matchLabels:
      app: top10songs
  replicas: 3
  template:
    metadata:
      labels:
        app: top10songs
    spec:
      containers:
        - name: top10songs
          image: patelman/my-top10-list:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: top10movies
spec:
  type: ClusterIP
  selector:
    app: top10movies
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: top10movies
spec:
  selector:
    matchLabels:
      app: top10movies
  replicas: 3
  template:
    metadata:
      labels:
        app: top10movies
    spec:
      containers:
        - name: top10movies
          image: patelman/my-top10-list:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: top10games
spec:
  type: ClusterIP
  selector:
    app: top10games
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: top10games
spec:
  selector:
    matchLabels:
      app: top10games
  replicas: 3
  template:
    metadata:
      labels:
        app: top10games
    spec:
      containers:
        - name: top10games
          image: patelman/my-top10-list:latest
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: top10-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /top10songs
            pathType: Prefix
            backend:
              service:
                name: top10songs
                port:
                  name: http
          - path: /top10movies
            pathType: Prefix
            backend:
              service:
                name: top10movies
                port:
                  name: http
          - path: /top10games
            pathType: Prefix
            backend:
              service:
                name: top10games
                port:
                  name: http
