name: Sysbench load test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup sysbench
        run: |
          if [ "${{ matrix.runner }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get -y install sysbench
          elif [ "${{ matrix.runner }}" = "macos-latest" ]; then
            brew install sysbench
          fi

      - name: Run sysbench load test
        run: sysbench cpu --threads=2 --time=60s

