name: Check for newer nginx container

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  check-for-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Check for newer nginx container
        uses: docker://docker.io/library/nginx:stable-alpine
        with:
          entrypoint: sh
          args: '-c "apk update && apk version nginx"'
        id: nginx_version_check
      - name: Print nginx update status
        run: |
          if [[ "${{ steps.nginx_version_check.outputs.stdout }}" == *'newer than'* ]]; then
            echo "A newer version of nginx is available"
          else
            echo "nginx is up to date"
          fi

