name: Check for newer nginx container

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-for-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Check for newer nginx container
        uses: docker://docker.io/library/nginx:stable-alpine
        with:
          entrypoint: sh
          args: '-c "apk update && apk info -u nginx"'
