
name: Webserver Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Docker credentials
          run: |
            echo $DOCKER_USERNAME
            echo $DOCKER_PASSWORD
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: ./github-actions/.
          push: true
          tags: patelman/my-top10-list:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

