name: Webserver Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: username/my-top10-list:latest
