
name: Webserver Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: ./github-actions/.
          push: false
          tags: patelman/my-top10-list:latest

      - name: Run Docker
        run: |
          docker run -d --name my-top10-list -p 80:80 patelman/my-top10-list:latest
          sleep 30

      - name: Test container
        run: |
          curl -I http://localhost/
          wget http://localhost/
          docker stop my-top10-list
